"""steps/utils/html_paper.py 的测试:ar5iv/arxiv LaTeXML HTML → Markdown + 扁平章节。"""

from steps.utils.html_paper import arxiv_html_to_markdown

# 典型 LaTeXML 结构缩样:文档标题/章节/子章节/段落/行内+独立公式/图+图注/表/跳过的页脚。
_HTML = """<!DOCTYPE html><html><head><title>x</title></head><body>
<article>
<h1 class="ltx_title ltx_title_document">Attention Is All You Need</h1>
<div class="ltx_abstract"><h6 class="ltx_title ltx_title_abstract">Abstract</h6>
<p class="ltx_p">The dominant sequence models are RNNs.</p></div>
<section class="ltx_section" id="S1">
<h2 class="ltx_title ltx_title_section"><span class="ltx_tag">1 </span>Introduction</h2>
<div class="ltx_para"><p class="ltx_p">Recurrent networks factor computation along
positions of a sequence.</p></div>
<section class="ltx_subsection" id="S1.SS1">
<h3 class="ltx_title ltx_title_subsection">1.1 Background</h3>
<p class="ltx_p">Attention weight <math alttext="\\alpha_{ij}" display="inline"><mi>a</mi></math> scales values.</p>
<math alttext="E=mc^2" display="block"><mrow><mi>E</mi></mrow></math>
<figure class="ltx_figure" id="S1.F1"><img src="assets/x1.png" alt="">
<figcaption class="ltx_caption">Figure 1: The Transformer architecture.</figcaption></figure>
<table class="ltx_tabular"><tr><th>Model</th><th>BLEU</th></tr>
<tr><td>Base</td><td>27.3</td></tr></table>
</section>
</section>
<footer class="ltx_page_footer"><p>Generated by LaTeXML noise</p></footer>
</article></body></html>"""


class TestArxivHtmlToMarkdown:
    def test_headings_and_structure(self):
        doc = arxiv_html_to_markdown(_HTML)
        md = doc["markdown"]
        assert "# Attention Is All You Need" in md
        assert "## 1 Introduction" in md
        assert "### 1.1 Background" in md
        assert doc["title"] == "Attention Is All You Need"

    def test_math_alttext(self):
        md = arxiv_html_to_markdown(_HTML)["markdown"]
        assert r"$\alpha_{ij}$" in md            # 行内:alttext 转 $…$
        assert "$$E=mc^2$$" in md                 # display=block:独立 $$…$$
        assert "<mi>" not in md                   # MathML 子树不漏入正文

    def test_figure_and_caption(self):
        md = arxiv_html_to_markdown(_HTML)["markdown"]
        assert "![](assets/x1.png)" in md
        assert "*Figure 1: The Transformer architecture.*" in md

    def test_table_best_effort(self):
        md = arxiv_html_to_markdown(_HTML)["markdown"]
        assert "| Model | BLEU |" in md
        assert "|---|---|" in md
        assert "| Base | 27.3 |" in md

    def test_skips_footer_noise(self):
        md = arxiv_html_to_markdown(_HTML)["markdown"]
        assert "LaTeXML noise" not in md

    def test_flat_sections_for_tree(self):
        secs = arxiv_html_to_markdown(_HTML)["sections"]
        titles = [s["title"] for s in secs]
        assert "1 Introduction" in titles
        assert "1.1 Background" in titles
        intro = next(s for s in secs if s["title"] == "1 Introduction")
        sub = next(s for s in secs if s["title"] == "1.1 Background")
        assert intro["level"] < sub["level"]      # 层级差保证 build_section_tree 正确嵌套
        assert "Recurrent networks" in intro["text"]

    def test_img_src_map_rewrite(self):
        html = '<body><img src="x9.png"></body>'
        md = arxiv_html_to_markdown(html, src_map={"x9.png": "assets/x9.png"})["markdown"]
        assert "![](assets/x9.png)" in md

    def test_unfetched_img_kept_as_is(self):
        html = '<body><img src="https://ar5iv.org/x.png"></body>'
        md = arxiv_html_to_markdown(html)["markdown"]
        assert "![](https://ar5iv.org/x.png)" in md


class TestPageChromeFiltered:
    """页级 chrome(arxiv 官方 HTML 弹窗/页眉脚)整树跳过,不混进正文(线上踩过:Report GitHub Issue 进译文)。"""

    def test_dialog_form_header_footer_skipped(self):
        html = (
            '<html><body>'
            '<dialog id="modal-form"><form><header class="modal-header">'
            '<h5>Report GitHub Issue</h5></header>Title: Describe the issue below:</form></dialog>'
            '<header class="arxiv-html-header">chrome nav</header>'
            '<article class="ltx_document"><h1 class="ltx_title">Real Title</h1>'
            '<p class="ltx_p">Body text.</p></article>'
            '<footer class="ds-site-footer">site footer</footer>'
            '</body></html>'
        )
        md = arxiv_html_to_markdown(html)["markdown"]
        assert 'Report GitHub Issue' not in md
        assert 'chrome nav' not in md and 'site footer' not in md
        assert 'Real Title' in md and 'Body text.' in md
