[package]
name = "flori-server"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
flori-core.workspace = true
flori-pipeline.workspace = true
flori-store = { path = "../flori-store", version = "=0.0.0" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
flori-runner = { path = "../flori-runner", version = "=0.0.0" }

[lints]
workspace = true
